#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Проверяем наличие композера
if (file_exists($autoload = __DIR__.'/vendor/autoload.php')) {
    require $autoload;
} else {
    echo "Composer dependencies not installed. Run 'composer install'.\n";
    exit(1);
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);